### PR TITLE
Fix #314: Make Setback Temperature and Setback hours per day truly optional

### LINKED ISSUE #314: Re-make these optional in Rules & JS: Setback Temperature and Setback hours per day
- [ ] Address recent feature regression in rules engine that makes it so these fields cannot be optional, especially in the last Rules Engine part.
- [ ] Restore zod type to .optional for these and/or remove the default.

Steve says this may be confusing to existing users if not optional

Image

### PR DESCRIPTION
**Pull request by chaoyi09**
## Summary
- Fix Zod schema to handle empty string form inputs for optional setback fields using `z.preprocess`
- Make `setbackTemperature` and `setbackHoursPerDay` nullable in Prisma schema (`Int` → `Int?`)
- Replace hardcoded defaults (`|| 65` / `|| 0`) with `?? null` in `createCase` and `updateCase`
- Handle null values in edit page (show empty field) and analysis display page (show "N/A")
- Allow users to clear previously filled setback values (change from filled → empty)

 ## Migration
- Added database migration to allow NULL values for setback fields 

## Test
- [x] Leave Setback Temperature and Setback hours per day empty → form submits successfully
- [x] Fill in setback fields → values are saved and displayed correctly
- [x] View case details with empty setback fields → shows "N/A"
- [x] Edit case with empty setback fields → fields remain empty (not pre-filled with defaults)
- [x] Edit case with filled setback fields → user can clear the values and they become "N/A"

- [x] add house values ,leave file unloaded → got to view cases page → “view” analysis for case → see that the house values are correct

### CODE REVIEW

File: heat-stack/prisma/migrations/20260206230306_make_setback_fields_optional/migration.sql [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+PRAGMA foreign_keys=OFF;
+CREATE TABLE "new_HeatingInput" (
+    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
+    "analysisId" INTEGER NOT NULL,
+    "fuelType" TEXT NOT NULL,
+    "designTemperatureOverride" BOOLEAN NOT NULL,
+    "heatingSystemEfficiency" INTEGER NOT NULL,
+    "thermostatSetPoint" INTEGER NOT NULL,
+    "setbackTemperature" INTEGER,
+    "setbackHoursPerDay" INTEGER,
```
Comment (wvansteen) [inline heat-stack/prisma/migrations/20260206230306_make_setback_fields_optional/migration.sql]: Nit: Since we're weakening the constraint, we could do this migration without a table create.
